### ISSUE TITLE
File versioning / CICD

### ISSUE THREAD

**Issue by alexiswl** [umccr/aws_parallel_cluster#1]
Mini flow diagram of how I intend to work this:

![LucidChartLink](https://lucid.app/publicSegments/view/11a883a6-2f12-40f5-ac18-4f7831a8916e/image.png)

**Comment by alexiswl** [comment]
LucidChart edit link: https://lucid.app/lucidchart/d75ab3f4-27d1-4307-b362-6220124191cb

**Comment by alexiswl** [comment]
@brainstorm does this look like an appropriate CI/CD diagram?

**Comment by brainstorm** [comment]
Hm, I need a bit more context and have some questions, let's chat tomorrow at the devops meetup? ;)

**Comment by alexiswl** [comment]
Sounds good, have uploaded a few ideas into the [dev branch](https://github.com/umccr/aws_parallel_cluster/tree/dev)

**Comment by brainstorm** [comment]
LGTM ;)
